### PR TITLE
Review from register CTRL9_XL

### PR DESCRIPTION
**Pull request by deddy11**
Hello, 
This is my next PR. Please spare your time to review it. 
Thanks.

### CODE REVIEW

**Review by cparata — COMMENTED** [review]
Hi @deddy11 ,
thanks for this PR. It seems to me that makes sense. I noticed that you changed the name to several enum and structures, so could you please update accordingly the ISM330DLCSensor.cpp file where these enum and structures are used? For example, when we call the "Enable_Double_Tap_Detection", now we need to use ISM330DLC_ACC_GYRO_INT1_DOUBLE_TAP_t enum, etc. Otherwise we can get compilation errors.
Thanks in advance and Best Regards,
Carlo

**Comment by deddy11** [comment]
Hi @cparata ,
thanks for your review. I will try to update again in a couple of days. Please kindly wait.
Thank you.

**Comment by deddy11** [comment]
Hello @cparata ,
I have pushed the changes. Please review it again. Actually I only want to use ISM330DLC_ACC_GYRO_Driver files to be used with ESP-IDF framework. That's why I didn't put much concern on ISM330DLCSensor files. But this time I have compiled all of the files. So I hope this time there is no more any error.
Thanks.

**Comment by cparata** [comment]
Hello @deddy11 ,
the new PR seems fine to me. I have also tested the hardware features of ISM330DLC and they seem working fine.
If you agree, I will generate a new release of the library.
Best Regards,
Carlo

**Comment by deddy11** [comment]
Hi @cparata ,
Yes, I agree. I'll wait for the new release.
Thank you.

**Comment by cparata** [comment]
Ok done!

**Pull request merged**
